[package]
name = "server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
aes-gcm = "0.10"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
sha2 = "0.11.0"
rand = "0.10.2"
